openapi: 3.0.0
info:
  version: 1.0.0
  title: Vizsgaremek Szerver API Dokumentáció
  description: A Vizsgaremek végpontjainek részeletes leírása és használata
servers:
  - url: http://localhost:3000
paths:
  /product:
    get:
      description: Returns a list of products
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /product/{product_id}:
    get:
      security:
        - bearerAuth: []
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Product:
      type: object
      required:
        - name
        - description
        - price
      properties:
        name:
          type: string
        description:
          type: string
        price:
          type: number
        category:
          type: object
          $ref: '#/components/schemas/Category'
    Category:
      type: object
      required:
        - name
        - description
      properties:
        name:
          type: string
        description:
          type: string